---
exclude: |
  ^node_modules/
  ^\.dvc/cache/
  ^\.dvc/tmp/
  ^outputs/
  ^artifacts/
  ^mlruns/
  ^mlartifacts/
  ^plots/
  ^\.venv/
  ^__pycache__/
default_install_hook_types: [commit-msg, pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-xml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii]
        exclude_types: [jupyter]
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=10240]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.11.0
    hooks:
      - id: black
        name: black (python)
        language_version: python3
        args: [--line-length=120]
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3
        args: [--profile, black, --line-length=120]
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8 (python)
        language_version: python3
        args: [--max-line-length=120]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict
          - -d
          - '{extends: relaxed, rules: {line-length: {max: 120}}}'
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.19.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
        args: [--failure-threshold, error]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.0
    hooks:
      - id: commitizen
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: [--format, gcc]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.2
    hooks:
      - id: nbstripout
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.2
    hooks:
      - id: sphinx-lint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier (format non-Python files)
        files: \.(js|jsx|ts|tsx|json|md|css|scss|html|graphql|mdx)$
        args: [--write]
