---
seed: 42
dataset:
  img_size: 224
  batch_size: 16
  num_workers: 2
  data_root: data/raw
train:
  max_epochs: 10
  lr: 1e-3
model:
  backbone: vit
  num_classes: 4
logging:
  mlflow_uri: http://127.0.0.1:5000
  experiment_name: corn_classifier_experiment
output:
  ckpt_dir: artifacts/checkpoints
